import type { Difficulty, TowerDefinition, TowerKind } from './gameTypes';

export const TOWER_DEFS: Record<TowerKind, TowerDefinition> = {
    dart: {
        kind: 'dart',
        name: 'Dart',
        difficulty: 'easy',
        range: 178,
        cooldown: 430,
        damage: 15,
        color: 0x3dcfff,
        accent: 0xffef77,
        description: 'fast shots',
    },
    cannon: {
        kind: 'cannon',
        name: 'Cannon',
        difficulty: 'easy',
        range: 158,
        cooldown: 1120,
        damage: 25,
        color: 0xffaa4d,
        accent: 0xffde8a,
        description: 'star splash',
    },
    missile: {
        kind: 'missile',
        name: 'Missile',
        difficulty: 'medium',
        range: 210,
        cooldown: 980,
        damage: 26,
        color: 0x7be05b,
        accent: 0xecff9a,
        description: 'homing impact',
    },
    laser: {
        kind: 'laser',
        name: 'Laser',
        difficulty: 'medium',
        range: 225,
        cooldown: 720,
        damage: 18,
        color: 0x47f6ea,
        accent: 0xffffff,
        description: 'reflecting beam',
    },
    ricochet: {
        kind: 'ricochet',
        name: 'Ricochet',
        difficulty: 'hard',
        range: 230,
        cooldown: 1120,
        damage: 20,
        color: 0x9274ff,
        accent: 0xff89f1,
        description: 'wall bouncer',
    },
    cluster: {
        kind: 'cluster',
        name: 'Cluster',
        difficulty: 'veryHard',
        range: 245,
        cooldown: 1500,
        damage: 22,
        color: 0xff6c8d,
        accent: 0xfff09b,
        description: 'confetti burst',
    },
    fire: {
        kind: 'fire',
        name: 'Fire',
        difficulty: 'veryHard',
        range: 220,
        cooldown: 1280,
        damage: 8,
        color: 0xff923b,
        accent: 0xfff05e,
        description: 'spreading glow',
    },
};

export const TOWER_KINDS_BY_DIFFICULTY: Record<Difficulty, TowerKind[]> = {
    easy: ['dart', 'cannon'],
    medium: ['missile', 'laser'],
    hard: ['ricochet'],
    veryHard: ['cluster', 'fire'],
};