import { VOCAB_EXTRA } from './vocabExtra';
import type { WordEntry } from './gameTypes';

const VOCAB: WordEntry[] = [
    {
        word: 'brave',
        difficulty: 'easy',
        shortDefinition: 'ready to face danger',
        definition: 'Showing courage when something is difficult or scary.',
        synonyms: ['courageous', 'bold', 'fearless'],
        antonyms: ['cowardly', 'timid'],
    },
    {
        word: 'calm',
        difficulty: 'easy',
        shortDefinition: 'peaceful and not upset',
        definition: 'Not excited, nervous, angry, or upset.',
        synonyms: ['peaceful', 'relaxed', 'serene'],
        antonyms: ['agitated', 'frantic'],
    },
    {
        word: 'clever',
        difficulty: 'easy',
        shortDefinition: 'quick to understand',
        definition: 'Able to learn, understand, or solve things quickly.',
        synonyms: ['smart', 'bright', 'sharp'],
        antonyms: ['dull', 'foolish'],
    },
    {
        word: 'honest',
        difficulty: 'easy',
        shortDefinition: 'truthful and fair',
        definition: 'Telling the truth and acting fairly.',
        synonyms: ['truthful', 'sincere', 'fair'],
        antonyms: ['dishonest', 'deceitful'],
    },
    {
        word: 'swift',
        difficulty: 'easy',
        shortDefinition: 'moving very fast',
        definition: 'Happening or moving quickly.',
        synonyms: ['quick', 'rapid', 'speedy'],
        antonyms: ['slow', 'sluggish'],
    },
    {
        word: 'sturdy',
        difficulty: 'easy',
        shortDefinition: 'strong and solid',
        definition: 'Strongly built and not easily broken.',
        synonyms: ['strong', 'tough', 'solid'],
        antonyms: ['weak', 'flimsy'],
    },
    {
        word: 'resilient',
        difficulty: 'medium',
        shortDefinition: 'able to recover',
        definition: 'Able to become strong or successful again after trouble.',
        synonyms: ['tough', 'adaptable', 'hardy'],
        antonyms: ['fragile', 'delicate'],
    },
    {
        word: 'scarce',
        difficulty: 'medium',
        shortDefinition: 'hard to find',
        definition: 'Not enough for demand; rare or in short supply.',
        synonyms: ['rare', 'limited', 'sparse'],
        antonyms: ['abundant', 'plentiful'],
    },
    {
        word: 'nimble',
        difficulty: 'medium',
        shortDefinition: 'quick and light in movement',
        definition: 'Able to move quickly, lightly, and easily.',
        synonyms: ['agile', 'spry', 'quick'],
        antonyms: ['clumsy', 'awkward'],
    },
    {
        word: 'frugal',
        difficulty: 'medium',
        shortDefinition: 'careful with money',
        definition: 'Careful about spending money or using resources.',
        synonyms: ['thrifty', 'economical', 'sparing'],
        antonyms: ['wasteful', 'extravagant'],
    },
    {
        word: 'precise',
        difficulty: 'medium',
        shortDefinition: 'exact and accurate',
        definition: 'Very exact, careful, and accurate.',
        synonyms: ['exact', 'accurate', 'careful'],
        antonyms: ['vague', 'inexact'],
    },
    {
        word: 'hostile',
        difficulty: 'medium',
        shortDefinition: 'unfriendly or opposed',
        definition: 'Very unfriendly or strongly against something.',
        synonyms: ['unfriendly', 'aggressive', 'opposed'],
        antonyms: ['friendly', 'welcoming'],
    },
    {
        word: 'ephemeral',
        difficulty: 'veryHard',
        shortDefinition: 'lasting briefly',
        definition: 'Lasting for only a very short time.',
        synonyms: ['brief', 'fleeting', 'transient'],
        antonyms: ['permanent', 'enduring'],
    },
    {
        word: 'austere',
        difficulty: 'veryHard',
        shortDefinition: 'plain or strict',
        definition: 'Severe, plain, and without comfort or decoration.',
        synonyms: ['severe', 'plain', 'stern'],
        antonyms: ['lavish', 'ornate'],
    },
    {
        word: 'ambiguous',
        difficulty: 'veryHard',
        shortDefinition: 'having more than one meaning',
        definition: 'Open to more than one interpretation; not clear.',
        synonyms: ['unclear', 'vague', 'equivocal'],
        antonyms: ['clear', 'obvious'],
    },
    {
        word: 'meticulous',
        difficulty: 'veryHard',
        shortDefinition: 'extremely careful',
        definition: 'Showing great attention to every detail.',
        synonyms: ['careful', 'thorough', 'painstaking'],
        antonyms: ['careless', 'sloppy'],
    },
    {
        word: 'obstinate',
        difficulty: 'veryHard',
        shortDefinition: 'stubbornly refusing to change',
        definition: 'Stubbornly holding to an opinion or course of action.',
        synonyms: ['stubborn', 'unyielding', 'headstrong'],
        antonyms: ['flexible', 'compliant'],
    },
    {
        word: 'volatile',
        difficulty: 'veryHard',
        shortDefinition: 'likely to change suddenly',
        definition: 'Likely to change suddenly and unpredictably.',
        synonyms: ['unstable', 'changeable', 'explosive'],
        antonyms: ['stable', 'steady'],
    },
];

export const ALL_VOCAB: WordEntry[] = [...VOCAB, ...VOCAB_EXTRA];