import type { Difficulty, WordEntry } from './gameTypes';

const e = (
    word: string,
    difficulty: Difficulty,
    shortDefinition: string,
    definition: string,
    synonyms: string[],
    antonyms: string[],
): WordEntry => ({
    word,
    difficulty,
    shortDefinition,
    definition,
    synonyms,
    antonyms,
});

export const VOCAB_EXTRA: WordEntry[] = [
    e('happy', 'easy', 'feeling good', 'Feeling pleased or joyful.', ['glad', 'joyful', 'cheerful'], ['sad', 'upset', 'miserable']),
    e('sad', 'easy', 'feeling unhappy', 'Feeling unhappy or sorry.', ['unhappy', 'upset', 'miserable'], ['happy', 'cheerful', 'glad']),
    e('fast', 'easy', 'moving quickly', 'Moving or happening quickly.', ['quick', 'speedy', 'swift'], ['slow', 'sluggish', 'unhurried']),
    e('slow', 'easy', 'not fast', 'Moving or happening without much speed.', ['unhurried', 'sluggish', 'gradual'], ['fast', 'quick', 'swift']),
    e('big', 'easy', 'large in size', 'Large in size or amount.', ['large', 'huge', 'giant'], ['small', 'tiny', 'little']),
    e('small', 'easy', 'little in size', 'Little in size or amount.', ['little', 'tiny', 'mini'], ['big', 'large', 'huge']),
    e('hot', 'easy', 'very warm', 'Having a high temperature.', ['warm', 'heated', 'boiling'], ['cold', 'cool', 'chilly']),
    e('cold', 'easy', 'not warm', 'Having a low temperature.', ['cool', 'chilly', 'freezing'], ['hot', 'warm', 'boiling']),
    e('kind', 'easy', 'nice to others', 'Helpful, gentle, and caring.', ['nice', 'caring', 'helpful'], ['mean', 'cruel', 'unkind']),
    e('mean', 'easy', 'unkind to others', 'Not kind or friendly.', ['unkind', 'cruel', 'nasty'], ['kind', 'nice', 'caring']),
    e('clean', 'easy', 'not dirty', 'Free from dirt or mess.', ['neat', 'fresh', 'spotless'], ['dirty', 'messy', 'grimy']),
    e('dirty', 'easy', 'not clean', 'Covered with dirt or mess.', ['messy', 'grimy', 'muddy'], ['clean', 'neat', 'spotless']),
    e('loud', 'easy', 'making much sound', 'Making a strong or noisy sound.', ['noisy', 'booming', 'blaring'], ['quiet', 'soft', 'silent']),
    e('quiet', 'easy', 'making little sound', 'Making little or no sound.', ['silent', 'soft', 'hushed'], ['loud', 'noisy', 'booming']),
    e('near', 'easy', 'close by', 'A short distance away.', ['close', 'nearby', 'beside'], ['far', 'distant', 'away']),
    e('far', 'easy', 'not close', 'A long distance away.', ['distant', 'away', 'remote'], ['near', 'close', 'nearby']),
    e('full', 'easy', 'holding all it can', 'Filled with as much as it can hold.', ['filled', 'packed', 'stuffed'], ['empty', 'bare', 'vacant']),
    e('empty', 'easy', 'having nothing inside', 'Having nothing or almost nothing inside.', ['bare', 'vacant', 'hollow'], ['full', 'filled', 'packed']),
    e('early', 'easy', 'before the time', 'Happening before the expected time.', ['prompt', 'ahead of time', 'soon'], ['late', 'delayed', 'behind time']),
    e('late', 'easy', 'after the time', 'Happening after the expected time.', ['delayed', 'behind time', 'tardy'], ['early', 'prompt', 'on time']),
    e('hard', 'easy', 'not soft', 'Firm and difficult to press or break.', ['solid', 'firm', 'tough'], ['soft', 'squishy', 'floppy']),
    e('soft', 'easy', 'easy to press', 'Not hard; easy to press, bend, or touch.', ['squishy', 'fluffy', 'smooth'], ['hard', 'firm', 'rough']),
    e('light', 'easy', 'not heavy', 'Not heavy; easy to lift.', ['lightweight', 'feathery', 'easy to lift'], ['heavy', 'weighty', 'hard to lift']),
    e('dark', 'easy', 'with little light', 'Having little or no light.', ['dim', 'shadowy', 'unlit'], ['bright', 'light', 'sunny']),
    e('open', 'easy', 'not closed', 'Not shut or covered.', ['not shut', 'uncovered', 'wide open'], ['closed', 'shut', 'locked']),
    e('closed', 'easy', 'shut', 'Shut so things cannot pass through.', ['shut', 'locked', 'sealed'], ['open', 'unlocked', 'unsealed']),
    e('safe', 'easy', 'free from danger', 'Protected from harm or danger.', ['protected', 'secure', 'harmless'], ['unsafe', 'dangerous', 'risky']),
    e('scary', 'easy', 'causing fear', 'Making someone feel afraid.', ['frightening', 'spooky', 'fearsome'], ['comforting', 'calm', 'friendly']),
    e('strong', 'easy', 'having power', 'Able to lift, hold, or last well.', ['powerful', 'tough', 'sturdy'], ['weak', 'fragile', 'flimsy']),
    e('weak', 'easy', 'not strong', 'Having little strength or power.', ['feeble', 'frail', 'flimsy'], ['strong', 'powerful', 'sturdy']),
    e('bright', 'easy', 'full of light', 'Giving off or filled with light.', ['shining', 'glowing', 'sunny'], ['dim', 'dark', 'dull']),
    e('dull', 'easy', 'not bright or exciting', 'Not bright or exciting.', ['dim', 'plain', 'boring'], ['bright', 'exciting', 'interesting']),
    e('quick', 'easy', 'done fast', 'Done or moving in a short time.', ['fast', 'rapid', 'swift'], ['slow', 'sluggish', 'unhurried']),
    e('gentle', 'easy', 'soft and kind', 'Careful, kind, and not rough.', ['kind', 'mild', 'careful'], ['rough', 'harsh', 'fierce']),
    e('tidy', 'easy', 'neat and ordered', 'Neat, clean, and in order.', ['neat', 'orderly', 'clean'], ['messy', 'untidy', 'dirty']),
    e('messy', 'easy', 'not tidy', 'Not neat or in order.', ['untidy', 'dirty', 'cluttered'], ['tidy', 'neat', 'orderly']),
    e('fresh', 'easy', 'new or clean', 'New, clean, or not old.', ['new', 'clean', 'crisp'], ['stale', 'old', 'spoiled']),
    e('stale', 'easy', 'not fresh', 'No longer fresh or new.', ['old', 'dry', 'not fresh'], ['fresh', 'new', 'crisp']),
    e('sweet', 'easy', 'like sugar', 'Tasting like sugar.', ['sugary', 'sweet-tasting', 'syrupy'], ['sour', 'bitter', 'sharp']),
    e('sour', 'easy', 'sharp tasting', 'Having a sharp, tart taste.', ['tart', 'sharp', 'tangy'], ['sweet', 'sugary', 'mild']),
    e('funny', 'easy', 'making people laugh', 'Silly or amusing.', ['silly', 'amusing', 'comic'], ['serious', 'solemn', 'not funny']),
    e('serious', 'easy', 'not silly', 'Not joking; needing care or thought.', ['sensible', 'important', 'solemn'], ['funny', 'silly', 'playful']),
    e('simple', 'easy', 'easy to understand', 'Easy to do or understand.', ['easy', 'plain', 'clear'], ['tricky', 'hard', 'complex']),
    e('tricky', 'easy', 'hard to do', 'Difficult because it needs care.', ['hard', 'difficult', 'puzzling'], ['simple', 'easy', 'clear']),

    e('curious', 'medium', 'wanting to know', 'Wanting to learn or find out.', ['interested', 'keen', 'wondering'], ['bored', 'uninterested', 'not curious']),
    e('eager', 'medium', 'excited to start', 'Very ready and excited to do something.', ['keen', 'excited', 'ready'], ['reluctant', 'unwilling', 'not keen']),
    e('patient', 'medium', 'able to wait calmly', 'Able to wait without getting upset.', ['calm', 'steady', 'willing to wait'], ['impatient', 'restless', 'hasty']),
    e('careful', 'medium', 'taking care', 'Doing something with attention to avoid mistakes.', ['cautious', 'watchful', 'thoughtful'], ['careless', 'reckless', 'sloppy']),
    e('fragile', 'medium', 'easy to break', 'Easily broken or damaged.', ['delicate', 'breakable', 'easy to break'], ['sturdy', 'strong', 'tough']),
    e('generous', 'medium', 'happy to share', 'Willing to give or share.', ['giving', 'kind', 'sharing'], ['selfish', 'stingy', 'greedy']),
    e('selfish', 'medium', 'thinking only of yourself', 'Caring mostly about yourself.', ['greedy', 'self-centred', 'thoughtless'], ['generous', 'sharing', 'kind']),
    e('loyal', 'medium', 'staying true', 'Faithful to a friend, group, or promise.', ['faithful', 'true', 'devoted'], ['disloyal', 'unfaithful', 'untrue']),
    e('lonely', 'medium', 'feeling alone', 'Sad because you are alone or without friends.', ['alone', 'isolated', 'left out'], ['included', 'together', 'welcomed']),
    e('proud', 'medium', 'pleased with yourself', 'Feeling pleased about something good you did or about someone you care about.', ['pleased', 'satisfied', 'glad'], ['ashamed', 'embarrassed', 'sorry']),
    e('humble', 'medium', 'not bragging', 'Not acting as if you are better than others.', ['modest', 'not boastful', 'simple'], ['proud', 'boastful', 'vain']),
    e('cheerful', 'medium', 'bright and happy', 'Happy and pleasant.', ['happy', 'sunny', 'merry'], ['gloomy', 'sad', 'grumpy']),
    e('gloomy', 'medium', 'dark or sad', 'Sad, dark, or without cheer.', ['sad', 'dark', 'dreary'], ['cheerful', 'bright', 'happy']),
    e('ancient', 'medium', 'very old', 'From a very long time ago.', ['old', 'very old', 'historic'], ['modern', 'new', 'recent']),
    e('modern', 'medium', 'from now', 'New or from the present time.', ['new', 'current', 'recent'], ['ancient', 'old', 'old-fashioned']),
    e('narrow', 'medium', 'not wide', 'Thin from side to side.', ['thin', 'slim', 'tight'], ['wide', 'broad', 'roomy']),
    e('shallow', 'medium', 'not deep', 'Having little depth.', ['not deep', 'low', 'surface-level'], ['deep', 'very deep', 'bottomless']),
    e('smooth', 'medium', 'not rough', 'Even and pleasant to touch.', ['even', 'silky', 'flat'], ['rough', 'bumpy', 'scratchy']),
    e('rough', 'medium', 'not smooth', 'Bumpy, uneven, or harsh.', ['bumpy', 'scratchy', 'uneven'], ['smooth', 'soft', 'even']),
    e('rapid', 'medium', 'very fast', 'Moving or happening very quickly.', ['fast', 'quick', 'speedy'], ['slow', 'sluggish', 'gradual']),
    e('sluggish', 'medium', 'moving slowly', 'Slow and lacking energy.', ['slow', 'lazy', 'drowsy'], ['rapid', 'quick', 'lively']),
    e('puzzled', 'medium', 'confused', 'Not sure because something is hard to understand.', ['confused', 'mixed-up', 'unsure'], ['certain', 'clear', 'sure']),
    e('certain', 'medium', 'sure', 'Sure that something is true.', ['sure', 'confident', 'positive'], ['unsure', 'doubtful', 'puzzled']),
    e('fierce', 'medium', 'strong and wild', 'Very strong, wild, or intense.', ['wild', 'intense', 'ferocious'], ['gentle', 'mild', 'calm']),
    e('ordinary', 'medium', 'usual', 'Normal or not special.', ['usual', 'normal', 'plain'], ['special', 'unusual', 'rare']),
    e('special', 'medium', 'not ordinary', 'Different in a good or important way.', ['unusual', 'important', 'unique'], ['ordinary', 'common', 'plain']),
    e('plentiful', 'medium', 'more than enough', 'Available in a large amount.', ['abundant', 'ample', 'lots of'], ['scarce', 'rare', 'limited']),
    e('wasteful', 'medium', 'using too much', 'Using more than is needed.', ['careless', 'extravagant', 'using too much'], ['careful', 'frugal', 'saving']),
    e('grateful', 'medium', 'thankful', 'Feeling or showing thanks.', ['thankful', 'appreciative', 'pleased'], ['ungrateful', 'unappreciative', 'rude']),
    e('grumpy', 'medium', 'bad-tempered', 'Easily annoyed or in a bad mood.', ['cranky', 'cross', 'grouchy'], ['cheerful', 'pleasant', 'happy']),
    e('cosy', 'medium', 'warm and snug', 'Comfortable, warm, and pleasant.', ['snug', 'comfortable', 'warm'], ['chilly', 'uncomfortable', 'cold']),
    e('chilly', 'medium', 'a little cold', 'Cool enough to feel cold.', ['cool', 'cold', 'nippy'], ['warm', 'cosy', 'hot']),
    e('active', 'medium', 'moving or busy', 'Busy, moving, or full of energy.', ['busy', 'lively', 'energetic'], ['idle', 'still', 'inactive']),
    e('idle', 'medium', 'not busy', 'Not working, moving, or being used.', ['still', 'inactive', 'unused'], ['active', 'busy', 'working']),
    e('flexible', 'medium', 'able to bend', 'Able to bend or change easily.', ['bendable', 'adaptable', 'limber'], ['stiff', 'rigid', 'fixed']),
    e('stiff', 'medium', 'hard to bend', 'Not easy to bend or move.', ['rigid', 'firm', 'tight'], ['flexible', 'limber', 'loose']),
    e('helpful', 'medium', 'giving help', 'Useful or willing to help.', ['useful', 'kind', 'supportive'], ['unhelpful', 'useless', 'harmful']),
    e('harmful', 'medium', 'causing damage', 'Able to hurt or damage.', ['dangerous', 'damaging', 'unsafe'], ['helpful', 'safe', 'useful']),
    e('cautious', 'medium', 'careful about danger', 'Careful to avoid danger or mistakes.', ['careful', 'wary', 'watchful'], ['reckless', 'careless', 'rash']),
    e('reckless', 'medium', 'not careful', 'Acting without thinking about danger.', ['careless', 'rash', 'wild'], ['cautious', 'careful', 'safe']),
    e('playful', 'medium', 'ready for fun', 'Full of fun and joking.', ['fun-loving', 'merry', 'frisky'], ['serious', 'solemn', 'stern']),
    e('weary', 'medium', 'very tired', 'Very tired in body or mind.', ['tired', 'sleepy', 'exhausted'], ['rested', 'lively', 'awake']),
    e('lively', 'medium', 'full of energy', 'Full of life and energy.', ['energetic', 'active', 'cheerful'], ['weary', 'dull', 'sleepy']),
    e('silent', 'medium', 'without sound', 'Making no sound.', ['quiet', 'hushed', 'soundless'], ['noisy', 'loud', 'talkative']),

    e('absurd', 'hard', 'silly in a strange way', 'So silly or strange that it seems impossible.', ['ridiculous', 'silly', 'foolish'], ['sensible', 'reasonable', 'wise']),
    e('abundant', 'hard', 'more than enough', 'Existing in a large amount.', ['plentiful', 'ample', 'lots of'], ['scarce', 'rare', 'limited']),
    e('accurate', 'hard', 'exactly right', 'Correct and free from mistakes.', ['correct', 'exact', 'precise'], ['wrong', 'inaccurate', 'false']),
    e('admire', 'hard', 'look up to', 'To respect or think well of someone.', ['respect', 'praise', 'appreciate'], ['dislike', 'mock', 'criticise']),
    e('anxious', 'hard', 'worried', 'Feeling worried or nervous.', ['worried', 'nervous', 'uneasy'], ['calm', 'relaxed', 'confident']),
    e('avoid', 'hard', 'keep away from', 'To stay away from something.', ['dodge', 'escape', 'keep away'], ['approach', 'meet', 'face']),
    e('brisk', 'hard', 'quick and lively', 'Quick, active, and full of energy.', ['quick', 'lively', 'energetic'], ['slow', 'sluggish', 'leisurely']),
    e('capture', 'hard', 'catch and hold', 'To catch or take control of something.', ['catch', 'seize', 'trap'], ['release', 'free', 'lose']),
    e('collapse', 'hard', 'fall down', 'To suddenly fall or cave in.', ['fall', 'crumple', 'topple'], ['stand', 'rise', 'stay up']),
    e('confident', 'hard', 'sure of yourself', 'Feeling sure that you can do something.', ['sure', 'bold', 'self-assured'], ['nervous', 'unsure', 'timid']),
    e('confuse', 'hard', 'make unclear', 'To make someone unable to understand.', ['puzzle', 'mix up', 'bewilder'], ['explain', 'clarify', 'clear up']),
    e('connect', 'hard', 'join together', 'To link or join things.', ['join', 'link', 'attach'], ['separate', 'divide', 'disconnect']),
    e('convince', 'hard', 'make someone believe', 'To cause someone to agree or believe.', ['persuade', 'assure', 'win over'], ['discourage', 'dissuade', 'make unsure']),
    e('create', 'hard', 'make something new', 'To make or bring something into being.', ['make', 'build', 'invent'], ['destroy', 'ruin', 'break']),
    e('damage', 'hard', 'hurt or break', 'To harm or make something worse.', ['harm', 'break', 'spoil'], ['repair', 'mend', 'fix']),
    e('defend', 'hard', 'protect from harm', 'To protect or speak for someone.', ['protect', 'guard', 'shield'], ['attack', 'harm', 'abandon']),
    e('delight', 'hard', 'make very happy', 'To make someone very happy.', ['please', 'thrill', 'charm'], ['upset', 'sadden', 'disappoint']),
    e('drowsy', 'hard', 'sleepy', 'Sleepy and ready to rest.', ['sleepy', 'tired', 'dozy'], ['awake', 'alert', 'lively']),
    e('elegant', 'hard', 'graceful and neat', 'Beautiful in a simple, graceful way.', ['graceful', 'stylish', 'neat'], ['messy', 'plain', 'clumsy']),
    e('enormous', 'hard', 'very large', 'Extremely big.', ['huge', 'giant', 'massive'], ['tiny', 'small', 'little']),
    e('examine', 'hard', 'look at closely', 'To look at or study carefully.', ['inspect', 'study', 'check'], ['ignore', 'skip', 'miss']),
    e('expand', 'hard', 'make bigger', 'To grow or make something larger.', ['grow', 'stretch', 'increase'], ['shrink', 'reduce', 'contract']),
    e('familiar', 'hard', 'known before', 'Known because you have seen or heard it before.', ['known', 'usual', 'recognised'], ['strange', 'new', 'unknown']),
    e('forbid', 'hard', 'say no to', 'To order that something is not allowed.', ['ban', 'prohibit', 'stop'], ['allow', 'permit', 'let']),
    e('frequent', 'hard', 'happening often', 'Happening many times.', ['common', 'regular', 'often'], ['rare', 'seldom', 'unusual']),
    e('genuine', 'hard', 'real', 'Real and not fake.', ['real', 'true', 'authentic'], ['fake', 'false', 'pretend']),
    e('glimpse', 'hard', 'quick look', 'A very quick look.', ['peek', 'glance', 'quick look'], ['stare', 'miss', 'ignore']),
    e('greedy', 'hard', 'wanting too much', 'Wanting more than you need.', ['selfish', 'grasping', 'grabby'], ['generous', 'sharing', 'content']),
    e('hesitate', 'hard', 'pause before acting', 'To stop briefly because you are unsure.', ['pause', 'wait', 'delay'], ['act', 'rush', 'continue']),
    e('improve', 'hard', 'make better', 'To become or make something better.', ['make better', 'upgrade', 'fix'], ['worsen', 'damage', 'spoil']),
    e('include', 'hard', 'make part of', 'To have as part of a group.', ['add', 'contain', 'involve'], ['exclude', 'remove', 'leave out']),
    e('interrupt', 'hard', 'stop someone briefly', 'To break into what someone is saying or doing.', ['stop', 'break in', 'disturb'], ['continue', 'allow', 'let finish']),
    e('jealous', 'hard', 'wanting what another has', 'Upset because someone else has something you want.', ['envious', 'resentful', 'wanting'], ['content', 'pleased', 'happy for others']),
    e('lopsided', 'hard', 'not even', 'Uneven or leaning to one side.', ['uneven', 'crooked', 'tilted'], ['balanced', 'even', 'straight']),
    e('magnificent', 'hard', 'very impressive', 'Very beautiful, grand, or impressive.', ['splendid', 'grand', 'wonderful'], ['plain', 'ordinary', 'unimpressive']),
    e('mend', 'hard', 'fix', 'To repair something broken.', ['fix', 'repair', 'patch'], ['break', 'damage', 'ruin']),
    e('mysterious', 'hard', 'hard to explain', 'Strange and not easy to understand.', ['strange', 'puzzling', 'secret'], ['clear', 'plain', 'known']),
    e('notice', 'hard', 'see or become aware', 'To see, hear, or become aware of something.', ['spot', 'observe', 'see'], ['miss', 'ignore', 'overlook']),
    e('observe', 'hard', 'watch carefully', 'To watch or notice carefully.', ['watch', 'notice', 'study'], ['ignore', 'miss', 'overlook']),
    e('peculiar', 'hard', 'strange or unusual', 'Different from what is normal.', ['odd', 'strange', 'unusual'], ['ordinary', 'normal', 'usual']),
    e('predict', 'hard', 'say what may happen', 'To say what you think will happen later.', ['guess', 'forecast', 'foretell'], ['remember', 'look back', 'be surprised']),
    e('protect', 'hard', 'keep safe', 'To keep someone or something safe.', ['guard', 'defend', 'shield'], ['harm', 'attack', 'endanger']),
    e('reduce', 'hard', 'make smaller', 'To make less or smaller.', ['decrease', 'lessen', 'shrink'], ['increase', 'expand', 'grow']),
    e('refuse', 'hard', 'say no', 'To say no or not accept.', ['decline', 'reject', 'deny'], ['accept', 'agree', 'allow']),
    e('reluctant', 'hard', 'not wanting to', 'Not eager or willing to do something.', ['unwilling', 'hesitant', 'not keen'], ['eager', 'willing', 'ready']),
    e('require', 'hard', 'need', 'To need or make necessary.', ['need', 'demand', 'call for'], ['not need', 'skip', 'make optional']),
    e('respect', 'hard', 'show honour', 'To treat someone as important and worthy.', ['honour', 'admire', 'value'], ['mock', 'insult', 'disrespect']),
    e('scatter', 'hard', 'spread around', 'To throw or spread in many directions.', ['spread', 'sprinkle', 'disperse'], ['gather', 'collect', 'cluster']),
    e('sensible', 'hard', 'showing good sense', 'Wise and practical.', ['wise', 'reasonable', 'practical'], ['absurd', 'foolish', 'silly']),
    e('separate', 'hard', 'move apart', 'To split or keep things apart.', ['divide', 'split', 'disconnect'], ['join', 'connect', 'combine']),

    e('adapt', 'veryHard', 'change to fit', 'To change so you can handle a new place, rule, or problem.', ['adjust', 'change', 'fit'], ['resist', 'refuse', 'stay the same']),
    e('ambitious', 'veryHard', 'wanting to achieve', 'Wanting to do something important or difficult.', ['determined', 'driven', 'eager'], ['lazy', 'unmotivated', 'idle']),
    e('analyse', 'veryHard', 'study carefully', 'To look at the parts of something to understand it.', ['study', 'examine', 'inspect'], ['guess', 'ignore', 'skim']),
    e('apologise', 'veryHard', 'say sorry', 'To say you are sorry for a mistake.', ['say sorry', 'regret', 'make amends'], ['blame', 'deny', 'boast']),
    e('astonish', 'veryHard', 'surprise greatly', 'To surprise someone very much.', ['amaze', 'surprise', 'startle'], ['bore', 'calm', 'leave unsurprised']),
    e('balanced', 'veryHard', 'steady and even', 'Even, steady, or fair on both sides.', ['steady', 'even', 'fair'], ['lopsided', 'uneven', 'unfair']),
    e('benefit', 'veryHard', 'help or good result', 'Something helpful, or the act of helping.', ['help', 'advantage', 'gain'], ['harm', 'loss', 'damage']),
    e('consider', 'veryHard', 'think about', 'To think carefully about something.', ['think', 'ponder', 'study'], ['ignore', 'dismiss', 'forget']),
    e('considerate', 'veryHard', 'thinking of others', 'Kind because you think about other people.', ['thoughtful', 'kind', 'caring'], ['thoughtless', 'selfish', 'rude']),
    e('contrast', 'veryHard', 'show differences', 'To compare things by showing how they are different.', ['compare', 'differentiate', 'set against'], ['match', 'blend', 'resemble']),
    e('cooperate', 'veryHard', 'work together', 'To work with others to reach a goal.', ['team up', 'help', 'work together'], ['argue', 'refuse', 'compete']),
    e('courageous', 'veryHard', 'very brave', 'Showing courage when something is hard or scary.', ['brave', 'bold', 'fearless'], ['timid', 'cowardly', 'fearful']),
    e('decrease', 'veryHard', 'become less', 'To become smaller or less.', ['lessen', 'reduce', 'drop'], ['increase', 'grow', 'expand']),
    e('demonstrate', 'veryHard', 'show how', 'To show or explain by doing.', ['show', 'display', 'explain'], ['hide', 'conceal', 'confuse']),
    e('determine', 'veryHard', 'decide firmly', 'To decide or find out for sure.', ['decide', 'settle', 'find out'], ['guess', 'doubt', 'hesitate']),
    e('diligent', 'veryHard', 'working carefully', 'Working hard and carefully.', ['hardworking', 'careful', 'steady'], ['lazy', 'careless', 'idle']),
    e('discover', 'veryHard', 'find out', 'To find or learn something new.', ['find', 'uncover', 'learn'], ['lose', 'miss', 'hide']),
    e('encourage', 'veryHard', 'give hope', 'To give someone confidence or support.', ['support', 'cheer', 'inspire'], ['discourage', 'stop', 'upset']),
    e('estimate', 'veryHard', 'make a careful guess', 'To make a sensible guess about an amount.', ['guess', 'approximate', 'judge'], ['measure exactly', 'know for sure', 'prove']),
    e('evidence', 'veryHard', 'proof', 'Facts or signs that help show what is true.', ['proof', 'clue', 'sign'], ['guess', 'rumour', 'opinion']),
    e('exhausted', 'veryHard', 'extremely tired', 'Very, very tired.', ['worn out', 'drained', 'weary'], ['rested', 'fresh', 'energetic']),
    e('fortunate', 'veryHard', 'lucky', 'Having good luck.', ['lucky', 'blessed', 'favoured'], ['unlucky', 'unfortunate', 'out of luck']),
    e('gradual', 'veryHard', 'happening slowly', 'Happening little by little.', ['slow', 'steady', 'step-by-step'], ['sudden', 'quick', 'instant']),
    e('ignore', 'veryHard', 'not notice on purpose', 'To pay no attention to something.', ['overlook', 'skip', 'dismiss'], ['notice', 'heed', 'listen']),
    e('imagine', 'veryHard', 'picture in your mind', 'To make a picture or idea in your mind.', ['picture', 'dream', 'suppose'], ['know', 'see', 'prove']),
    e('increase', 'veryHard', 'become more', 'To become larger or greater.', ['grow', 'expand', 'rise'], ['decrease', 'reduce', 'shrink']),
    e('independent', 'veryHard', 'doing things yourself', 'Able to do things without much help.', ['self-reliant', 'free', 'able'], ['dependent', 'needy', 'helpless']),
    e('inspire', 'veryHard', 'make someone want to try', 'To fill someone with a wish to do something good.', ['encourage', 'motivate', 'uplift'], ['discourage', 'dishearten', 'stop']),
    e('investigate', 'veryHard', 'look for the truth', 'To search carefully to find out what happened.', ['study', 'explore', 'examine'], ['ignore', 'skip', 'guess']),
    e('migrate', 'veryHard', 'move to a new place', 'To move from one place to another, often by season.', ['move', 'travel', 'relocate'], ['stay', 'settle', 'remain']),
    e('misplace', 'veryHard', 'put in the wrong place', 'To lose something by putting it somewhere and forgetting.', ['lose', 'mislay', 'put in wrong place'], ['find', 'keep', 'put away']),
    e('necessary', 'veryHard', 'needed', 'Needed or required.', ['needed', 'required', 'essential'], ['unneeded', 'extra', 'optional']),
    e('persevere', 'veryHard', 'keep trying', 'To keep trying even when something is hard.', ['persist', 'continue', 'keep trying'], ['quit', 'stop', 'give up']),
    e('possible', 'veryHard', 'can happen', 'Able to happen or be done.', ['doable', 'achievable', 'can happen'], ['impossible', 'unable', 'out of reach']),
    e('prepare', 'veryHard', 'get ready', 'To get ready for something.', ['get ready', 'plan', 'arrange'], ['neglect', 'forget', 'leave unready']),
    e('previous', 'veryHard', 'before now', 'Happening or coming before.', ['earlier', 'former', 'past'], ['next', 'later', 'future']),
    e('reliable', 'veryHard', 'can be trusted', 'Able to be trusted to do what is expected.', ['dependable', 'trustworthy', 'steady'], ['unreliable', 'untrustworthy', 'unsteady']),
    e('rescue', 'veryHard', 'save from danger', 'To save someone from danger.', ['save', 'free', 'help'], ['abandon', 'endanger', 'trap']),
    e('resourceful', 'veryHard', 'good at solving problems', 'Able to find clever ways to solve problems.', ['clever', 'inventive', 'capable'], ['helpless', 'stuck', 'unprepared']),
    e('responsible', 'veryHard', 'trusted to do the right thing', 'Able to be trusted with duties or choices.', ['dependable', 'trustworthy', 'careful'], ['careless', 'irresponsible', 'reckless']),
    e('reveal', 'veryHard', 'show what was hidden', 'To make something known or visible.', ['show', 'uncover', 'display'], ['hide', 'conceal', 'cover']),
    e('sincere', 'veryHard', 'honest and real', 'Honest in feelings or words.', ['honest', 'genuine', 'true'], ['fake', 'false', 'insincere']),
    e('solution', 'veryHard', 'answer to a problem', 'The answer or way to fix a problem.', ['answer', 'fix', 'remedy'], ['problem', 'puzzle', 'mistake']),
    e('transparent', 'veryHard', 'easy to see through', 'Clear enough to see through.', ['clear', 'see-through', 'glass-like'], ['opaque', 'cloudy', 'hidden']),
];
